version: 2

defaults: &defaults
  working_directory: ~/tdc-discourse-seed
  docker:
    - image: circleci/node:8.9.1

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      
      - persist_to_workspace:
          root: ~/tdc-discourse-seed
          paths:
            - ./*
  
  seed_staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tdc-discourse-seed
      - run: bash seed.sh staging
