version: 2

defaults: &defaults
  working_directory: ~/tdc-discourse-seed
  docker:
    - image: circleci/node:8.9.1

jobs:
  seed_staging:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: bash seed.sh staging

  seed_production:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: bash seed.sh production

workflows:
  version: 2
  seed:
    jobs:
      - hold:
          type: approval
          filters:
            branches: 
              only:
                - development
                - master
      - seed_staging:
          requires:
            - hold
          filters:
            branches:
              only:
                - development
      - seed_production:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
